# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-07 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('companyName', models.CharField(max_length=50, verbose_name='Comapny Name')),
                ('comapnylocation', models.CharField(max_length=100, verbose_name='Company Location')),
                ('totalEmployee', models.IntegerField(default=0, verbose_name='Total Number of Employee')),
                ('created_by', models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, related_name='company_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=35, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('employeeName', models.CharField(max_length=50, verbose_name='Name of Employee')),
                ('employeeRole', models.CharField(max_length=25, verbose_name='ROle of Employee')),
                ('employeeAge', models.IntegerField(verbose_name='Age of an Employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Company')),
                ('created_by', models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, related_name='employeedetails_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=35, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeedetails_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobOpenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('roleName', models.CharField(max_length=100, verbose_name='Job Name')),
                ('associatedCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Company')),
                ('created_by', models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, related_name='jobopenings_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=35, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobopenings_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
