# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-07 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=50, verbose_name='Company Name'),
        ),
    ]
