# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-07 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_auto_20170807_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miapp.JobOpenings'),
            preserve_default=False,
        ),
    ]
