# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_auto_20170807_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.JobOpenings'),
        ),
    ]
